"""
ExportAgent: Agentic refactor for Export phase (RDL, TWBX)
"""
from io import BytesIO
from typing import Any, Dict, Optional
import zipfile
from enum import Enum

class ExportFormat(Enum):
    RDL = "rdl"
    TWBX = "twbx"


class ValidationHook:
    def pre_export(self, model: Any, target_format: ExportFormat) -> None:
        return

    def post_export(self, content: Any, target_format: ExportFormat) -> Dict[str, Any]:
        return {}


class LineageTracker:
    def capture(self, model: Any, target_format: ExportFormat) -> list[Dict[str, Any]]:
        return []


class RDLExporter:
    def __init__(self, config: Dict[str, Any]):
        self.config = config

    def export(self, model: Any, options: Dict[str, Any]) -> Dict[str, Any]:
        rdl_xml = self._resolve_rdl_xml(model)
        return {
            "content": rdl_xml.encode("utf-8"),
            "format": "rdl",
            "metadata": {"filename": f"{self._safe_name(model)}.rdl"},
            "validation": {"is_valid": True, "errors": [], "warnings": []},
        }

    def _safe_name(self, model: Any) -> str:
        if isinstance(model, dict):
            value = str(model.get("name") or model.get("dashboard_name") or "export").strip()
            return value or "export"
        return str(getattr(model, "name", "export") or "export").strip() or "export"

    def _resolve_rdl_xml(self, model: Any) -> str:
        if isinstance(model, bytes):
            return model.decode("utf-8", errors="ignore")
        if isinstance(model, str):
            return model
        if isinstance(model, dict):
            for key in ("rdl_xml", "rdl", "content", "xml"):
                value = model.get(key)
                if isinstance(value, bytes):
                    return value.decode("utf-8", errors="ignore")
                if isinstance(value, str) and value.strip():
                    return value
        return (
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
            "<Report xmlns=\"http://schemas.microsoft.com/sqlserver/reporting/2016/01/reportdefinition\">"
            "<Description>Generated by ExportAgent</Description>"
            "</Report>"
        )


class TWBXExporter:
    def __init__(self, config: Dict[str, Any]):
        self.config = config

    def export(self, model: Any, options: Dict[str, Any]) -> Dict[str, Any]:
        with BytesIO() as buffer:
            with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
                archive.writestr("workbook.twb", "<workbook version=\"18.1\"></workbook>")
            payload = buffer.getvalue()
        return {
            "content": payload,
            "format": "twbx",
            "metadata": {"filename": f"{self._safe_name(model)}.twbx"},
            "validation": {"is_valid": True, "errors": [], "warnings": []},
        }

    def _safe_name(self, model: Any) -> str:
        if isinstance(model, dict):
            value = str(model.get("name") or model.get("dashboard_name") or "export").strip()
            return value or "export"
        return str(getattr(model, "name", "export") or "export").strip() or "export"

class ExportAgent:
    """
    Agent principal d'export coordonnant les différents exporteurs (RDL, TWBX, ...)
    """
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.validation_hook = ValidationHook()
        self.lineage_tracker = LineageTracker()
        self.exporters = {
            ExportFormat.RDL: RDLExporter(config),
            ExportFormat.TWBX: TWBXExporter(config),
        }
    def export(self, model: Any, target_format: ExportFormat, options: Optional[Dict[str, Any]] = None) -> Dict:
        options = options or {}
        if target_format not in self.exporters:
            raise ValueError(f"Format {target_format} not supported")
        exporter = self.exporters[target_format]
        # Validation pré-export
        self.validation_hook.pre_export(model, target_format)
        result = exporter.export(model, options)
        # Validation post-export
        result["validation"] = self.validation_hook.post_export(result["content"], target_format)
        # Lineage
        result["lineage"] = self.lineage_tracker.capture(model, target_format)
        return result

    def run(self, step: Dict[str, Any]) -> Dict[str, Any]:
        """Legacy orchestrator compatibility (`agent.run(step)`)."""
        model = (step.get("inputs") or {}).get("artifacts") or {}
        result = self.export(model, ExportFormat.RDL)
        validation = result.get("validation") or {}
        status = "passed"
        if isinstance(validation, dict) and (validation.get("error") or validation.get("errors")):
            status = "failed"
        result["validation_status"] = status
        return result
